import * as THREE from './three.module.js';
const $=s=>document.querySelector(s), count=5;
const works=[
 {title:'Face à la Joconde',ratio:958/1248,x:0,z:-6.83,rotation:0,description:'Un personnage aux cheveux blancs contemple la Joconde, au milieu de roses intenses et de tons orangés.'},
 {title:'Vinyles au crépuscule',ratio:1054/760,x:-5.83,z:-3.2,rotation:Math.PI/2,description:'Deux personnages au bord de l’eau, des vinyles et une ville au coucher du soleil. La musique traverse toute la scène.'},
 {title:'Le cœur en bleu',ratio:948/682,x:5.83,z:-3.2,rotation:-Math.PI/2,description:'Une silhouette aux cheveux turquoise, les bras ouverts, tient un cœur rouge dans un espace parcouru de bleus.'},
 {title:'Une nuit en musique',ratio:1022/748,x:-5.83,z:3.3,rotation:Math.PI/2,description:'Une scène d’intérieur aux couleurs vives, entourée de pochettes d’albums, de disques et d’une guitare.'},
 {title:'Danse cosmique',ratio:730/582,x:5.83,z:3.3,rotation:-Math.PI/2,description:'Des silhouettes flottent entre des îlots et un astre rouge incandescent, sur un fond noir étoilé.'}
].map((w,i)=>({...w,image:['joconde.png','coupleeau.png','eaucoeur.png','musiquechambre.png','espace.png'][i],h:i===0?2.9:2.05,w:(i===0?2.9:2.05)*w.ratio}));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let selected=0,visiting=false,guided=false,tourElapsed=0,scene,camera,renderer,raycaster,floorMesh,hoverRing,artMeshes=[],transition=null,keys=new Set(),yaw=0,pitch=0,targetYaw=0,targetPitch=0;
const current=new THREE.Vector3(1.3,1.72,9),target=current.clone(), pointer=new THREE.Vector2();
function number(i){return String(i+1).padStart(2,'0')}function stopTour(){guided=false;tourElapsed=0;$('#autotour').textContent='▷ Visite guidée';$('#autotour').setAttribute('aria-pressed','false');$('#tourprogress').style.width='0'}
function setVisiting(){visiting=true;document.body.classList.add('visiting')}
function updateLabels(){let w=works[selected];$('#position').textContent='LA GALERIE / '+number(selected);$('#counter').textContent=number(selected)+' / 05';$('.scene-label span').textContent=number(selected)+' — 05';$('.scene-label p').textContent=w.title;document.querySelectorAll('#mapButtons button').forEach((b,i)=>b.classList.toggle('current',i===selected));}
function safePath(a,b){
 // Keep guided travel outside the bench footprint.
 let crosses=false;
 for(let i=0;i<=60;i++){let p=a.clone().lerp(b,i/60);if(Math.abs(p.x)<2.05&&p.z>2.35&&p.z<4.3){crosses=true;break}}
 if(!crosses)return [a,b];
 const side=(a.x+b.x>=0?1:-1)*2.5;
 if((a.z>4.3&&b.z<2.35)||(b.z>4.3&&a.z<2.35))return [a,new THREE.Vector3(side,1.72,a.z),new THREE.Vector3(side,1.72,b.z),b];
 const bypass=a.z<2.35||b.z<2.35?1.9:4.75;
 return [a,new THREE.Vector3(a.x,1.72,bypass),new THREE.Vector3(b.x,1.72,bypass),b];
}
function onPath(points,t){const lengths=points.slice(1).map((p,i)=>p.distanceTo(points[i])),total=lengths.reduce((a,b)=>a+b,0);let d=t*total;for(let i=0;i<lengths.length;i++){if(d<=lengths[i]||i===lengths.length-1)return points[i].clone().lerp(points[i+1],lengths[i]?d/lengths[i]:1);d-=lengths[i]}return points.at(-1)}
function angleNear(value,base){return base+Math.atan2(Math.sin(value-base),Math.cos(value-base))}
function go(i,automatic=false){if(!automatic)stopTour();selected=(i+count)%count;setVisiting();const w=works[selected],n=new THREE.Vector3(Math.sin(w.rotation),0,Math.cos(w.rotation));const distance=selected>=3?(innerWidth<700?Math.min(3.5,w.w*1.2):3.15):(innerWidth<700?Math.max(3.7,w.w*1.2):4.1);const dest=new THREE.Vector3(w.x,1.72,w.z).addScaledVector(n,distance);target.copy(dest);targetYaw=angleNear(Math.atan2(-n.x,n.z),yaw);targetPitch=Math.atan2(2.6-1.72,distance);transition={from:current.clone(),to:dest.clone(),yawFrom:yaw,yawTo:targetYaw,pitchFrom:pitch,pitchTo:targetPitch,t:0};tourElapsed=0;updateLabels();$('#artHint').style.display='block';}
function openDetail(i){stopTour();selected=(i+count)%count;let w=works[selected];$('#detailImage').src=w.image;$('#detailImage').alt='Clevart — '+w.title;$('#detailTitle').textContent=w.title;$('#detailNumber').textContent='ŒUVRE '+number(selected)+' / TITRE DESCRIPTIF';$('#description').textContent=w.description;$('.detail-image').classList.remove('zoomed');$('#zoom').textContent='Agrandir ＋';if($('#works').open)$('#works').close();if(!$('#detail').open)$('#detail').showModal()}
works.forEach((w,i)=>{const b=document.createElement('button');b.className='work-card';b.innerHTML=`<img src="${w.image}" alt="Clevart — ${w.title}"><h3>${w.title}</h3><span>0${i+1} / Rejoindre le tableau →</span>`;b.onclick=()=>{$('#works').close();go(i)};$('#workGrid').append(b);const m=document.createElement('button');m.textContent=number(i);m.setAttribute('aria-label','Rejoindre '+w.title);m.style.left=(i===0?50:i%2?14:86)+'%';m.style.top=(i===0?8:i<3?27:66)+'%';m.onclick=()=>go(i);$('#mapButtons').append(m)});
$('#collection').onclick=()=>{stopTour();$('#works').showModal()};$('#fallbackCollection').onclick=()=>$('#works').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>{if(d.id==='detail')go(selected)});d.addEventListener('click',e=>{if(e.target===d){let r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
$('#detailPrev').onclick=()=>openDetail(selected-1);$('#detailNext').onclick=()=>openDetail(selected+1);function zoom(){let a=$('.detail-image').classList.toggle('zoomed');$('#zoom').textContent=a?'Réduire −':'Agrandir ＋'}$('#zoom').onclick=zoom;$('#detailImage').onclick=zoom;
$('#help').onclick=()=>{$('#guide').hidden=!$('#guide').hidden;stopTour()};$('#closeGuide').onclick=()=>$('#guide').hidden=true;
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}};
$('#enter').onclick=()=>go(0);$('#next').onclick=()=>go(visiting?selected+1:0);$('#previous').onclick=()=>go(visiting?selected-1:4);$('#artHint').onclick=()=>openDetail(selected);
$('#autotour').onclick=()=>{if(guided)stopTour();else{go(visiting?selected:0,true);guided=true;$('#autotour').textContent='Ⅱ Mettre en pause';$('#autotour').setAttribute('aria-pressed','true')}};
$('#hideui').onclick=()=>{document.body.classList.add('contemplating');$('#restoreui').hidden=false};$('#restoreui').onclick=()=>{document.body.classList.remove('contemplating');$('#restoreui').hidden=true};
$('#overview').onclick=()=>{stopTour();visiting=false;document.body.classList.remove('visiting');target.set(1.3,1.72,9);targetYaw=angleNear(-.08,yaw);targetPitch=.015;transition={from:current.clone(),to:target.clone(),yawFrom:yaw,yawTo:targetYaw,pitchFrom:pitch,pitchTo:targetPitch,t:0};$('#position').textContent='LE VESTIBULE';$('#counter').textContent='Visite libre';$('.scene-label p').textContent='Des histoires en couleurs.'};
function free(){if(transition){target.copy(current);targetYaw=yaw;targetPitch=pitch;transition=null}stopTour();setVisiting();$('#position').textContent='PROMENADE LIBRE';$('#counter').textContent='Visite libre'}
function move(forward,side,dt){free();let nx=target.x+(Math.sin(targetYaw)*forward+Math.cos(targetYaw)*side)*dt,nz=target.z+(-Math.cos(targetYaw)*forward+Math.sin(targetYaw)*side)*dt;nx=THREE.MathUtils.clamp(nx,-5.05,5.05);nz=THREE.MathUtils.clamp(nz,-5.8,10.5);if(!(Math.abs(nx)<1.9&&nz>2.5&&nz<4.15)){target.x=nx;target.z=nz}}
const movementKeys=['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','z','q'];window.addEventListener('keydown',e=>{if($('dialog[open]')||e.target.closest('button,a,input'))return;let k=e.key.toLowerCase();if(movementKeys.includes(k)){e.preventDefault();keys.add(k)}if(e.key==='Escape')$('#restoreui').click()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();if(document.hidden)stopTour()});
let pad=null;document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();pad=b.dataset.move;b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>pad=null});
try{
scene=new THREE.Scene();scene.background=new THREE.Color('#f4f5f2');scene.fog=new THREE.Fog('#f4f5f2',24,55);camera=new THREE.PerspectiveCamera(innerWidth<700?65:54,innerWidth/innerHeight,.08,70);camera.position.copy(current);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;$('#scene').append(renderer.domElement);raycaster=new THREE.Raycaster();
const wall=new THREE.MeshStandardMaterial({color:0xf6f5f1,roughness:.9}),floor=new THREE.MeshStandardMaterial({color:0xd5d6ce,roughness:.28,metalness:.12}),trim=new THREE.MeshStandardMaterial({color:0xe6e5df,roughness:.8}),dark=new THREE.MeshStandardMaterial({color:0x373831,roughness:.6});
function box(w,h,d,x,y,z,mat=wall){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.receiveShadow=true;m.castShadow=true;scene.add(m);return m}
floorMesh=box(12,.2,25,0,-.11,5.3,floor);box(12,6,.2,0,3,-7);box(.2,6,25,-6,3,5.3);box(.2,6,25,6,3,5.3);box(12,.2,25,0,6,5.3);
for(let h of [.13,4.65,4.82]){box(12,.09,.1,0,h,-6.87,trim);box(.1,.09,24,-5.87,h,5,trim);box(.1,.09,24,5.87,h,5,trim)}
for(let z of [-6.65,.1,6.65,12])for(let x of [-5.83,5.83]){box(.14,4.7,.28,x,2.35,z,trim);box(.21,.16,.42,x,4.55,z,trim);box(.21,.2,.42,x,.12,z,trim)}
for(let z=-5;z<15;z+=4){box(12,.2,.23,0,5.75,z,trim);box(4.4,.04,2.9,0,5.88,z+1.7,new THREE.MeshBasicMaterial({color:0xffffff}));for(let x of [-4.4,4.4]){box(.055,.06,3.5,x,5.62,z+1.7,dark);for(let dz of [.6,2.8])box(.17,.15,.22,x,5.5,z+dz,dark)}}
scene.add(new THREE.HemisphereLight(0xffffff,0xa2a393,2.15));const sun=new THREE.DirectionalLight(0xfff8e9,2.5);sun.position.set(-3,5,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10});sun.shadow.normalBias=.035;scene.add(sun);
const loader=new THREE.TextureLoader();
works.forEach((w,i)=>{const group=new THREE.Group();group.position.set(w.x,2.6,w.z);group.rotation.y=w.rotation;scene.add(group);const frame=new THREE.Mesh(new THREE.BoxGeometry(w.w+.10,w.h+.10,.12),dark);frame.castShadow=true;frame.receiveShadow=true;group.add(frame);const tex=loader.load(w.image,()=>{},undefined,()=>{const card=document.querySelectorAll('.work-card span')[i];card.textContent='Image indisponible'});tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();const painting=new THREE.Mesh(new THREE.PlaneGeometry(w.w,w.h),new THREE.MeshBasicMaterial({map:tex,toneMapped:false}));painting.position.z=.067;painting.userData.work=i;group.add(painting);artMeshes.push(painting);const plaque=new THREE.Mesh(new THREE.BoxGeometry(.35,.18,.014),wall);plaque.position.set(w.w/2+.31,-w.h/2+.1,0);group.add(plaque);const spot=new THREE.SpotLight(0xfff4dd,23,10,.68,.8,1.7);spot.position.set(w.x+Math.sin(w.rotation)*1.3,5.35,w.z+Math.cos(w.rotation)*1.3);spot.target=group;scene.add(spot)});
box(3.3,.19,.72,0,.49,3.3,dark);for(let x of [-1.3,1.3])box(.12,.42,.53,x,.21,3.3,dark);
const joint=new THREE.MeshStandardMaterial({color:0xbfc2b8,roughness:1});for(let z=-6;z<17;z+=2.8)box(12,.002,.012,0,-.008,z,joint);for(let x=-4;x<6;x+=2)box(.012,.002,25,x,-.008,5.3,joint);
hoverRing=new THREE.Mesh(new THREE.RingGeometry(.22,.25,48),new THREE.MeshBasicMaterial({color:0x727c66,transparent:true,opacity:.65,side:THREE.DoubleSide}));hoverRing.rotation.x=-Math.PI/2;hoverRing.visible=false;scene.add(hoverRing);
function hits(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects([...artMeshes,floorMesh])}
let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,yaw:targetYaw,pitch:targetPitch,drag:false};renderer.domElement.setPointerCapture(e.pointerId)});
renderer.domElement.addEventListener('pointermove',e=>{if(down){let dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.abs(dx)+Math.abs(dy)>7&&!down.drag){free();down.yaw=targetYaw;down.pitch=targetPitch;down.drag=true}if(down.drag){targetYaw=down.yaw-dx*.004;targetPitch=THREE.MathUtils.clamp(down.pitch+dy*.003,-.8,.8);hoverRing.visible=false}}else{const hit=hits(e)[0];renderer.domElement.style.cursor=hit?.object.userData.work!==undefined?'pointer':hit?'crosshair':'grab';hoverRing.visible=!!hit&&hit.object===floorMesh;if(hoverRing.visible){hoverRing.position.copy(hit.point);hoverRing.position.y=.003}}});
renderer.domElement.addEventListener('pointerup',e=>{if(down&&!down.drag){let hit=hits(e)[0];if(hit?.object.userData.work!==undefined){let i=hit.object.userData.work;if(visiting&&selected===i&&!transition&&current.distanceTo(new THREE.Vector3(works[i].x,1.72,works[i].z))<4.8)openDetail(i);else go(i)}else if(hit?.object===floorMesh){free();let x=THREE.MathUtils.clamp(hit.point.x,-5,5),z=THREE.MathUtils.clamp(hit.point.z,-5.8,10.5);if(!(Math.abs(x)<1.9&&z>2.5&&z<4.15)){target.set(x,1.72,z);transition={from:current.clone(),to:target.clone(),yawFrom:yaw,yawTo:targetYaw,pitchFrom:pitch,pitchTo:targetPitch,t:0}}}}down=null});renderer.domElement.addEventListener('pointercancel',()=>down=null);renderer.domElement.addEventListener('pointerleave',()=>hoverRing.visible=false);
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();move(-Math.sign(e.deltaY),0,.45)},{passive:false});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<700?65:54;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let last=performance.now();function animate(now){let dt=Math.min((now-last)/1000,.05);last=now;if(!$('dialog[open]')){let f=(keys.has('w')||keys.has('z')||keys.has('arrowup')||pad==='forward'?1:0)-(keys.has('s')||keys.has('arrowdown')||pad==='back'?1:0),s=(keys.has('d')||keys.has('arrowright')||pad==='right'?1:0)-(keys.has('a')||keys.has('q')||keys.has('arrowleft')||pad==='left'?1:0);if(f||s){let norm=Math.hypot(f,s);move(f/norm,s/norm,dt*2.4)}if(guided&&!transition){tourElapsed+=dt;$('#tourprogress').style.width=`${Math.min(tourElapsed/10,1)*90}%`;if(tourElapsed>=10)go(selected+1,true)}}
if(transition){transition.t=Math.min(1,transition.t+dt/(reduced?.01:2.15));let t=transition.t,t2=t*t*(3-2*t);if(!transition.path)transition.path=safePath(transition.from,transition.to);current.copy(onPath(transition.path,t2));yaw=THREE.MathUtils.lerp(transition.yawFrom,transition.yawTo,t2);pitch=THREE.MathUtils.lerp(transition.pitchFrom,transition.pitchTo,t2);if(t===1)transition=null}else{let t=reduced?1:1-Math.exp(-9*dt);current.lerp(target,t);yaw+=(targetYaw-yaw)*t;pitch+=(targetPitch-pitch)*t}camera.position.copy(current);camera.rotation.order='YXZ';camera.rotation.set(pitch,-yaw,0);$('#mapPosition').setAttribute('cx',String(60+current.x*7.5));$('#mapPosition').setAttribute('cy',String(18+(current.z+7)*6.7));renderer.render(scene,camera);requestAnimationFrame(animate)}requestAnimationFrame(animate);
}catch(e){console.error(e);$('#fallback').hidden=false;$('#intro').style.display='none';$('#artHint').style.display='none';$('#enter').disabled=true;document.querySelectorAll('.work-card').forEach((b,i)=>b.onclick=()=>openDetail(i))}
