const $=s=>document.querySelector(s);
let player=null,ready=false,apiPromise=null,currentId="PLIqSPDbNIT2I",loading=false;
const panel=$('#musicPanel'),status=$('#musicStatus');
function musicState(playing){window.dispatchEvent(new CustomEvent('clevart-music-state',{detail:{playing}}));document.body.classList.toggle('music-playing',playing)}
function say(s){status.textContent=s}function controls(active){document.querySelectorAll('[data-audio]').forEach(b=>b.disabled=!active);$('#musicVolume').disabled=!active}
function open(){panel.hidden=false;document.body.classList.add('music-open');$('#musicToggle').setAttribute('aria-expanded','true');$('#musicClose').focus();if(!player&&!loading)loadPlaylist()}
$('#musicToggle').onclick=()=>panel.hidden?open():close();window.addEventListener('clevart-open-music',open);
function close(){musicState(false);if(ready)player.pauseVideo();panel.hidden=true;document.body.classList.remove('music-open');$('#musicToggle').setAttribute('aria-expanded','false');$('#musicToggle').focus()}$('#musicClose').onclick=close;

function api(){if(window.YT?.Player)return Promise.resolve();if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{let timeout=setTimeout(()=>{apiPromise=null;reject(new Error('timeout'))},15000);window.onYouTubeIframeAPIReady=()=>{clearTimeout(timeout);resolve()};let old=document.querySelector('script[data-youtube-api]');old?.remove();let tag=document.createElement('script');tag.dataset.youtubeApi='true';tag.src='https://www.youtube.com/iframe_api';tag.onerror=()=>{clearTimeout(timeout);apiPromise=null;reject(new Error('network'))};document.head.append(tag)});return apiPromise}
function cue(){musicState(false);player.cuePlaylist({listType:'playlist',list:currentId,index:0});player.setLoop(true);player.setVolume(Number($('#musicVolume').value));controls(true);$('#musicPlay').textContent='Lire';say('Playlist prête. Appuie sur Lire.');}
function error(event){musicState(false);const messages={2:'Le lien ou la playlist est invalide.',5:'Cette vidéo ne peut pas être lue dans ce navigateur.',100:'Cette vidéo est privée ou indisponible. Essaie le morceau suivant.',101:'La lecture de cette vidéo est interdite sur les autres sites. Essaie le morceau suivant.',150:'La lecture de cette vidéo est interdite sur les autres sites. Essaie le morceau suivant.',153:'YouTube ne peut pas identifier ce lecteur. Ouvre le site depuis son adresse en ligne.'};say(messages[event.data]||'Impossible de lire cette playlist. Vérifie qu’elle est publique ou non répertoriée.');$('#musicPlay').textContent='Lire';}
async function loadPlaylist(){if(loading)return;loading=true;say('Connexion à YouTube…');try{await api();if(player&&ready)cue();else{player?.destroy();$('#youtubeHost').innerHTML='<div id="youtubePlayer"></div>';player=new YT.Player('youtubePlayer',{width:'100%',height:200,playerVars:{playsinline:1,controls:1,origin:location.origin,autoplay:0},events:{onReady(){ready=true;cue()},onStateChange(e){musicState(e.data===1);if(e.data===1){$('#musicPlay').textContent='Pause';const title=player.getVideoData()?.title;$('#musicTrack').textContent=title||'Lecture en cours';say('Lecture en continu.')}else if(e.data===2){$('#musicPlay').textContent='Lire';say('Lecture en pause.')}else if(e.data===3)say('Chargement du morceau…');else if(e.data===5){$('#musicPlay').textContent='Lire';say('Playlist prête. Appuie sur Lire.')}},onError:error,onAutoplayBlocked(){musicState(false);say('Appuie sur Lire ou sur le bouton du lecteur YouTube.')}}})}}catch{say('YouTube ne répond pas. Vérifie ta connexion ou ton bloqueur de contenu, puis réessaie.')}finally{loading=false;if(!ready){$('#musicPlay').disabled=false;$('#musicPlay').textContent='Réessayer'}}};
$('#musicPlay').onclick=()=>{if(!ready){loadPlaylist();return}if(player.getPlayerState()===1)player.pauseVideo();else player.playVideo()};$('#musicPrev').onclick=()=>{if(ready)player.previousVideo()};$('#musicNext').onclick=()=>{if(ready)player.nextVideo()};$('#musicVolume').oninput=e=>{if(ready)player.setVolume(Number(e.target.value))};controls(false);
